apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
data:
  GIT_SYNC_USERNAME: 
  GIT_SYNC_PASSWORD: 
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-ssh-secret
data:
  # key needs to be gitSshKey
  gitSshKey: 

