apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
  labels:
    tier: airflow
    component: mysql
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
  - port: {{ .Values.mysql.port }}
  selector:
    app: {{ .Release.Name }}-mysql
  type: {{ .Values.mysql.serviceType }}