# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysqlairflow
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./customcnf:/etc/mysql/conf.d
